/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentNFT"
      | "deposit"
      | "getBalance"
      | "getTotalDeposited"
      | "owner"
      | "pathUsdAddress"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "rescueVault"
      | "setAgentNFT"
      | "setPathUsdAddress"
      | "setUsdcAddress"
      | "transferOwnership"
      | "unpause"
      | "usdcAddress"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentNFTUpdated"
      | "Deposited"
      | "OwnershipTransferred"
      | "PathUsdAddressUpdated"
      | "Paused"
      | "Unpaused"
      | "UsdcAddressUpdated"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agentNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDeposited",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pathUsdAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueVault",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPathUsdAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUsdcAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agentNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pathUsdAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPathUsdAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUsdcAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usdcAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AgentNFTUpdatedEvent {
  export type InputTuple = [newAgentNFT: AddressLike];
  export type OutputTuple = [newAgentNFT: string];
  export interface OutputObject {
    newAgentNFT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    owner: AddressLike,
    agentId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    agentId: bigint,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    owner: string;
    agentId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PathUsdAddressUpdatedEvent {
  export type InputTuple = [newPathUsd: AddressLike];
  export type OutputTuple = [newPathUsd: string];
  export interface OutputObject {
    newPathUsd: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsdcAddressUpdatedEvent {
  export type InputTuple = [newUsdc: AddressLike];
  export type OutputTuple = [newUsdc: string];
  export interface OutputObject {
    newUsdc: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    owner: AddressLike,
    agentId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    agentId: bigint,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    owner: string;
    agentId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentVault extends BaseContract {
  connect(runner?: ContractRunner | null): AgentVault;
  waitForDeployment(): Promise<this>;

  interface: AgentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentNFT: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<
    [agentId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<
    [owner: AddressLike, agentId: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;

  getTotalDeposited: TypedContractMethod<
    [owner: AddressLike],
    [[bigint, bigint] & { usdcTotal: bigint; pathTotal: bigint }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pathUsdAddress: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueVault: TypedContractMethod<
    [
      user: AddressLike,
      agentId: BigNumberish,
      token: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setAgentNFT: TypedContractMethod<
    [_agentNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  setPathUsdAddress: TypedContractMethod<
    [_pathUsd: AddressLike],
    [void],
    "nonpayable"
  >;

  setUsdcAddress: TypedContractMethod<
    [_usdc: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdcAddress: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [agentId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [agentId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<
    [owner: AddressLike, agentId: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalDeposited"
  ): TypedContractMethod<
    [owner: AddressLike],
    [[bigint, bigint] & { usdcTotal: bigint; pathTotal: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pathUsdAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueVault"
  ): TypedContractMethod<
    [
      user: AddressLike,
      agentId: BigNumberish,
      token: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentNFT"
  ): TypedContractMethod<[_agentNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPathUsdAddress"
  ): TypedContractMethod<[_pathUsd: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUsdcAddress"
  ): TypedContractMethod<[_usdc: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [agentId: BigNumberish, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentNFTUpdated"
  ): TypedContractEvent<
    AgentNFTUpdatedEvent.InputTuple,
    AgentNFTUpdatedEvent.OutputTuple,
    AgentNFTUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PathUsdAddressUpdated"
  ): TypedContractEvent<
    PathUsdAddressUpdatedEvent.InputTuple,
    PathUsdAddressUpdatedEvent.OutputTuple,
    PathUsdAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UsdcAddressUpdated"
  ): TypedContractEvent<
    UsdcAddressUpdatedEvent.InputTuple,
    UsdcAddressUpdatedEvent.OutputTuple,
    UsdcAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentNFTUpdated(address)": TypedContractEvent<
      AgentNFTUpdatedEvent.InputTuple,
      AgentNFTUpdatedEvent.OutputTuple,
      AgentNFTUpdatedEvent.OutputObject
    >;
    AgentNFTUpdated: TypedContractEvent<
      AgentNFTUpdatedEvent.InputTuple,
      AgentNFTUpdatedEvent.OutputTuple,
      AgentNFTUpdatedEvent.OutputObject
    >;

    "Deposited(address,uint256,address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PathUsdAddressUpdated(address)": TypedContractEvent<
      PathUsdAddressUpdatedEvent.InputTuple,
      PathUsdAddressUpdatedEvent.OutputTuple,
      PathUsdAddressUpdatedEvent.OutputObject
    >;
    PathUsdAddressUpdated: TypedContractEvent<
      PathUsdAddressUpdatedEvent.InputTuple,
      PathUsdAddressUpdatedEvent.OutputTuple,
      PathUsdAddressUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UsdcAddressUpdated(address)": TypedContractEvent<
      UsdcAddressUpdatedEvent.InputTuple,
      UsdcAddressUpdatedEvent.OutputTuple,
      UsdcAddressUpdatedEvent.OutputObject
    >;
    UsdcAddressUpdated: TypedContractEvent<
      UsdcAddressUpdatedEvent.InputTuple,
      UsdcAddressUpdatedEvent.OutputTuple,
      UsdcAddressUpdatedEvent.OutputObject
    >;

    "Withdrawn(address,uint256,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
