/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentStrategy {
  export type StrategyStruct = {
    strategyType: BigNumberish;
    tokenIds: BigNumberish[];
    maxPosition: BigNumberish;
    stopLoss: BigNumberish;
    takeProfit: BigNumberish;
    frequency: BigNumberish;
    usePathusd: boolean;
    active: boolean;
    updatedAt: BigNumberish;
  };

  export type StrategyStructOutput = [
    strategyType: bigint,
    tokenIds: bigint[],
    maxPosition: bigint,
    stopLoss: bigint,
    takeProfit: bigint,
    frequency: bigint,
    usePathusd: boolean,
    active: boolean,
    updatedAt: bigint
  ] & {
    strategyType: bigint;
    tokenIds: bigint[];
    maxPosition: bigint;
    stopLoss: bigint;
    takeProfit: bigint;
    frequency: bigint;
    usePathusd: boolean;
    active: boolean;
    updatedAt: bigint;
  };
}

export interface AgentStrategyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentNFT"
      | "getStrategy"
      | "hasStrategy"
      | "owner"
      | "renounceOwnership"
      | "setAgentNFT"
      | "setStrategy"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentNFTUpdated"
      | "OwnershipTransferred"
      | "StrategyUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agentNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategy",
    values: [BigNumberish, AgentStrategy.StrategyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "agentNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentNFTUpdatedEvent {
  export type InputTuple = [newAgentNFT: AddressLike];
  export type OutputTuple = [newAgentNFT: string];
  export interface OutputObject {
    newAgentNFT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    strategyType: BigNumberish,
    active: boolean,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    strategyType: bigint,
    active: boolean,
    updatedAt: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    strategyType: bigint;
    active: boolean;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentStrategy extends BaseContract {
  connect(runner?: ContractRunner | null): AgentStrategy;
  waitForDeployment(): Promise<this>;

  interface: AgentStrategyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentNFT: TypedContractMethod<[], [string], "view">;

  getStrategy: TypedContractMethod<
    [agentId: BigNumberish],
    [AgentStrategy.StrategyStructOutput],
    "view"
  >;

  hasStrategy: TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgentNFT: TypedContractMethod<
    [_agentNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  setStrategy: TypedContractMethod<
    [agentId: BigNumberish, strategy: AgentStrategy.StrategyStruct],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStrategy"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [AgentStrategy.StrategyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasStrategy"
  ): TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentNFT"
  ): TypedContractMethod<[_agentNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStrategy"
  ): TypedContractMethod<
    [agentId: BigNumberish, strategy: AgentStrategy.StrategyStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentNFTUpdated"
  ): TypedContractEvent<
    AgentNFTUpdatedEvent.InputTuple,
    AgentNFTUpdatedEvent.OutputTuple,
    AgentNFTUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StrategyUpdated"
  ): TypedContractEvent<
    StrategyUpdatedEvent.InputTuple,
    StrategyUpdatedEvent.OutputTuple,
    StrategyUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentNFTUpdated(address)": TypedContractEvent<
      AgentNFTUpdatedEvent.InputTuple,
      AgentNFTUpdatedEvent.OutputTuple,
      AgentNFTUpdatedEvent.OutputObject
    >;
    AgentNFTUpdated: TypedContractEvent<
      AgentNFTUpdatedEvent.InputTuple,
      AgentNFTUpdatedEvent.OutputTuple,
      AgentNFTUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StrategyUpdated(uint256,address,uint8,bool,uint256)": TypedContractEvent<
      StrategyUpdatedEvent.InputTuple,
      StrategyUpdatedEvent.OutputTuple,
      StrategyUpdatedEvent.OutputObject
    >;
    StrategyUpdated: TypedContractEvent<
      StrategyUpdatedEvent.InputTuple,
      StrategyUpdatedEvent.OutputTuple,
      StrategyUpdatedEvent.OutputObject
    >;
  };
}
