/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TempoLeaderboard {
  export type AgentStatsStruct = {
    agentId: BigNumberish;
    owner: AddressLike;
    pnlUsd: BigNumberish;
    pnlBps: BigNumberish;
    tradeCount: BigNumberish;
    winCount: BigNumberish;
    tvl: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type AgentStatsStructOutput = [
    agentId: bigint,
    owner: string,
    pnlUsd: bigint,
    pnlBps: bigint,
    tradeCount: bigint,
    winCount: bigint,
    tvl: bigint,
    lastUpdated: bigint
  ] & {
    agentId: bigint;
    owner: string;
    pnlUsd: bigint;
    pnlBps: bigint;
    tradeCount: bigint;
    winCount: bigint;
    tvl: bigint;
    lastUpdated: bigint;
  };
}

export interface TempoLeaderboardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAgentStats"
      | "getTopAgents"
      | "getTotalStats"
      | "keeper"
      | "owner"
      | "renounceOwnership"
      | "setKeeper"
      | "transferOwnership"
      | "updateStats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "KeeperUpdated"
      | "OwnershipTransferred"
      | "StatsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAgentStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopAgents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStats",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "keeper", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStats",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAgentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setKeeper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStats",
    data: BytesLike
  ): Result;
}

export namespace KeeperUpdatedEvent {
  export type InputTuple = [newKeeper: AddressLike];
  export type OutputTuple = [newKeeper: string];
  export interface OutputObject {
    newKeeper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatsUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    pnlUsd: BigNumberish,
    pnlBps: BigNumberish,
    tradeCount: BigNumberish,
    winCount: BigNumberish,
    tvl: BigNumberish,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    pnlUsd: bigint,
    pnlBps: bigint,
    tradeCount: bigint,
    winCount: bigint,
    tvl: bigint,
    updatedAt: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    pnlUsd: bigint;
    pnlBps: bigint;
    tradeCount: bigint;
    winCount: bigint;
    tvl: bigint;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TempoLeaderboard extends BaseContract {
  connect(runner?: ContractRunner | null): TempoLeaderboard;
  waitForDeployment(): Promise<this>;

  interface: TempoLeaderboardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAgentStats: TypedContractMethod<
    [agentId: BigNumberish],
    [TempoLeaderboard.AgentStatsStructOutput],
    "view"
  >;

  getTopAgents: TypedContractMethod<
    [count: BigNumberish],
    [TempoLeaderboard.AgentStatsStructOutput[]],
    "view"
  >;

  getTotalStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalTvl: bigint;
        totalTrades: bigint;
        uniqueAgents: bigint;
      }
    ],
    "view"
  >;

  keeper: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setKeeper: TypedContractMethod<[_keeper: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateStats: TypedContractMethod<
    [
      agentId: BigNumberish,
      agentOwner: AddressLike,
      pnlUsd: BigNumberish,
      pnlBps: BigNumberish,
      tradeCount: BigNumberish,
      winCount: BigNumberish,
      tvl: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAgentStats"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [TempoLeaderboard.AgentStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopAgents"
  ): TypedContractMethod<
    [count: BigNumberish],
    [TempoLeaderboard.AgentStatsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalTvl: bigint;
        totalTrades: bigint;
        uniqueAgents: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "keeper"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKeeper"
  ): TypedContractMethod<[_keeper: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStats"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      agentOwner: AddressLike,
      pnlUsd: BigNumberish,
      pnlBps: BigNumberish,
      tradeCount: BigNumberish,
      winCount: BigNumberish,
      tvl: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "KeeperUpdated"
  ): TypedContractEvent<
    KeeperUpdatedEvent.InputTuple,
    KeeperUpdatedEvent.OutputTuple,
    KeeperUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StatsUpdated"
  ): TypedContractEvent<
    StatsUpdatedEvent.InputTuple,
    StatsUpdatedEvent.OutputTuple,
    StatsUpdatedEvent.OutputObject
  >;

  filters: {
    "KeeperUpdated(address)": TypedContractEvent<
      KeeperUpdatedEvent.InputTuple,
      KeeperUpdatedEvent.OutputTuple,
      KeeperUpdatedEvent.OutputObject
    >;
    KeeperUpdated: TypedContractEvent<
      KeeperUpdatedEvent.InputTuple,
      KeeperUpdatedEvent.OutputTuple,
      KeeperUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StatsUpdated(uint256,address,int256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      StatsUpdatedEvent.InputTuple,
      StatsUpdatedEvent.OutputTuple,
      StatsUpdatedEvent.OutputObject
    >;
    StatsUpdated: TypedContractEvent<
      StatsUpdatedEvent.InputTuple,
      StatsUpdatedEvent.OutputTuple,
      StatsUpdatedEvent.OutputObject
    >;
  };
}
