/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TokenPresaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "NUM_TOKENS"
      | "addPresale"
      | "buy"
      | "claim"
      | "claimEnabled"
      | "getPresaleInfo"
      | "getRaisedAmounts"
      | "getUserAllocation"
      | "owner"
      | "pathUsdAddress"
      | "pause"
      | "paused"
      | "presales"
      | "renounceOwnership"
      | "setClaimEnabled"
      | "setPathUsdAddress"
      | "setPresaleActive"
      | "setTreasury"
      | "setUsdcAddress"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "usdcAddress"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimEnabled"
      | "Claimed"
      | "FundsWithdrawn"
      | "OwnershipTransferred"
      | "Paused"
      | "PresaleAdded"
      | "Purchased"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "NUM_TOKENS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addPresale",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimEnabled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPresaleInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRaisedAmounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAllocation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pathUsdAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "presales",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimEnabled",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPathUsdAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPresaleActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUsdcAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "NUM_TOKENS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addPresale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPresaleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaisedAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pathUsdAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "presales", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPathUsdAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPresaleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUsdcAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usdcAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace ClaimEnabledEvent {
  export type InputTuple = [tokenId: BigNumberish, enabled: boolean];
  export type OutputTuple = [tokenId: bigint, enabled: boolean];
  export interface OutputObject {
    tokenId: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    claimer: AddressLike,
    tokenId: BigNumberish,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    claimer: string,
    tokenId: bigint,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    claimer: string;
    tokenId: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, to: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresaleAddedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    tokenAddress: AddressLike,
    price: BigNumberish,
    hardCap: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    tokenAddress: string,
    price: bigint,
    hardCap: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    tokenAddress: string;
    price: bigint;
    hardCap: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    tokenId: BigNumberish,
    usdcAmount: BigNumberish,
    tokenAmount: BigNumberish,
    paymentToken: AddressLike
  ];
  export type OutputTuple = [
    buyer: string,
    tokenId: bigint,
    usdcAmount: bigint,
    tokenAmount: bigint,
    paymentToken: string
  ];
  export interface OutputObject {
    buyer: string;
    tokenId: bigint;
    usdcAmount: bigint;
    tokenAmount: bigint;
    paymentToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenPresale extends BaseContract {
  connect(runner?: ContractRunner | null): TokenPresale;
  waitForDeployment(): Promise<this>;

  interface: TokenPresaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NUM_TOKENS: TypedContractMethod<[], [bigint], "view">;

  addPresale: TypedContractMethod<
    [
      tokenId: BigNumberish,
      tokenAddress: AddressLike,
      presalePrice: BigNumberish,
      hardCap: BigNumberish,
      endTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  buy: TypedContractMethod<
    [tokenId: BigNumberish, usdcAmount: BigNumberish, usePathusd: boolean],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  claimEnabled: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getPresaleInfo: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        token: string;
        price: bigint;
        raised: bigint;
        cap: bigint;
        endTime: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getRaisedAmounts: TypedContractMethod<[], [bigint[]], "view">;

  getUserAllocation: TypedContractMethod<
    [user: AddressLike, tokenId: BigNumberish],
    [[bigint, bigint] & { usdcPaid: bigint; tokenAmount: bigint }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pathUsdAddress: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  presales: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        tokenAddress: string;
        presalePrice: bigint;
        hardCap: bigint;
        endTime: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setClaimEnabled: TypedContractMethod<
    [tokenId: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setPathUsdAddress: TypedContractMethod<
    [_pathUsd: AddressLike],
    [void],
    "nonpayable"
  >;

  setPresaleActive: TypedContractMethod<
    [tokenId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setUsdcAddress: TypedContractMethod<
    [_usdc: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdcAddress: TypedContractMethod<[], [string], "view">;

  withdrawFunds: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NUM_TOKENS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addPresale"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      tokenAddress: AddressLike,
      presalePrice: BigNumberish,
      hardCap: BigNumberish,
      endTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [tokenId: BigNumberish, usdcAmount: BigNumberish, usePathusd: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimEnabled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getPresaleInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        token: string;
        price: bigint;
        raised: bigint;
        cap: bigint;
        endTime: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRaisedAmounts"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserAllocation"
  ): TypedContractMethod<
    [user: AddressLike, tokenId: BigNumberish],
    [[bigint, bigint] & { usdcPaid: bigint; tokenAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pathUsdAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "presales"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        tokenAddress: string;
        presalePrice: bigint;
        hardCap: bigint;
        endTime: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setClaimEnabled"
  ): TypedContractMethod<
    [tokenId: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPathUsdAddress"
  ): TypedContractMethod<[_pathUsd: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPresaleActive"
  ): TypedContractMethod<
    [tokenId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUsdcAddress"
  ): TypedContractMethod<[_usdc: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ClaimEnabled"
  ): TypedContractEvent<
    ClaimEnabledEvent.InputTuple,
    ClaimEnabledEvent.OutputTuple,
    ClaimEnabledEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PresaleAdded"
  ): TypedContractEvent<
    PresaleAddedEvent.InputTuple,
    PresaleAddedEvent.OutputTuple,
    PresaleAddedEvent.OutputObject
  >;
  getEvent(
    key: "Purchased"
  ): TypedContractEvent<
    PurchasedEvent.InputTuple,
    PurchasedEvent.OutputTuple,
    PurchasedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ClaimEnabled(uint256,bool)": TypedContractEvent<
      ClaimEnabledEvent.InputTuple,
      ClaimEnabledEvent.OutputTuple,
      ClaimEnabledEvent.OutputObject
    >;
    ClaimEnabled: TypedContractEvent<
      ClaimEnabledEvent.InputTuple,
      ClaimEnabledEvent.OutputTuple,
      ClaimEnabledEvent.OutputObject
    >;

    "Claimed(address,uint256,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256,address)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PresaleAdded(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      PresaleAddedEvent.InputTuple,
      PresaleAddedEvent.OutputTuple,
      PresaleAddedEvent.OutputObject
    >;
    PresaleAdded: TypedContractEvent<
      PresaleAddedEvent.InputTuple,
      PresaleAddedEvent.OutputTuple,
      PresaleAddedEvent.OutputObject
    >;

    "Purchased(address,uint256,uint256,uint256,address)": TypedContractEvent<
      PurchasedEvent.InputTuple,
      PurchasedEvent.OutputTuple,
      PurchasedEvent.OutputObject
    >;
    Purchased: TypedContractEvent<
      PurchasedEvent.InputTuple,
      PurchasedEvent.OutputTuple,
      PurchasedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
